#!/bin/bash

nvcc src/$1.cu -o build/$1 -I/usr/local/include -O3 -Xcompiler -fno-strict-aliasing --expt-extended-lambda --expt-relaxed-constexpr -Xcompiler -fopenmp -L/usr/local/lib/ -lGrid -lz -lcrypto -lmpfr -lgmp -lstdc++ -lm -lcuda
